{% set name = "cosmic_profiles" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc7e9246f39dc40b173642e731c4b71817b474865b99d2d995a6e0dd0406823e

build:
  script_env:
    - OMPI_MCA_plm_rsh_agent=  # [linux]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - setuptools
    - cython
    - cythongsl
    - numpy >=1.19.2
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - scikit-learn
    - cython
    - cythongsl
    - mpi4py
    - pathos
    - h5py <3.2  # [linux]
    - h5py  # [osx]
    - h5py  # [win]
    - psutil
    - openmpi =4.0.4  # [linux]
    - mpich  # [osx]
    - libgomp  # [linux]
    - llvm-openmp  # [osx]

test:
  imports:
    - cosmic_profiles
  source_files:
    - cosmic_profiles/tests
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest cosmic_profiles/tests  # [linux and osx]

about:
  home: https://github.com/tibordome/cosmic_profiles
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Implements 3D point cloud algorithms for estimation and fitting of shape and density profiles
  dev_url: https://github.com/tibordome/cosmic_profiles

extra:
  recipe-maintainers:
    - tibordome
